Vishal1003/Algorithms

selsort.cpp
=> selsort.cpp

MergeSort.cpp
I have added mergesort algorithm assign it to be @Vishal1003
=> implemented mergesort algorithm in cpp

CountingSort.cpp
I've provided implementation for Counting Sort , with necessary explanatory comments where ever necessary
=> CountingSort

Counting Sort/Implementation using C++, Counting Sort/Pseudo Code - Documentation
I have created a separate directory for counting sort.
In that directory, there are two files. 
1) Pseudo code
2) Implementation
I have created a separate directory for clean code and easy access.
Please merge this pull request.
=> PR for #7: Added Documentation of Counting Sort #7

binarysearch.cpp
As there was documentation present in the readme, added only the cpp program.
=> Added binary search program

InterpolationSearch.cpp
Implement Interpolation Search #15
=> Created InterpolationSearch.cpp

JumpSearch.cpp
Implementation of Jump Search #14
=> Created JumpSearch.cpp

README.md
Update the exponential search part of the README.md
=> Solve #28 Documentation of Exponential Search

README.md, kadaneAlgo.md, kadaneAlgorithm.cpp
=> Added Kadane's Algorithm

README.md, kruskalAlgo.cpp, kruskalAlgo.md
=> Added documentation and Implementation of Kruskal's Algorithm (Minimum Spanning Tree)

HeapSort.cpp, Inorder,Preorder and Postorder Traversal.cpp, Inorder,Preorder and Postorder Traversal.md
Inorder,Preorder and Postorder tree traversal implemented with proper comments and a documentation file.
=> Inorder,Preorder and Postorder tree traversal

kruskals Algorithm/kruskal.cpp, kruskals Algorithm/readme.md
Hey there I completed the implementation of Kruskal . Please merege. @Vishal1003
=> adding Kruskals algorithm

FloydWarshall Algorithm/floydwarshall.cpp, FloydWarshall Algorithm/floydwarshall.java
Please lemme know if any changes needed
**Happy** **Hacktoberfest** **^^**
=> Added FloydWarshall Algorithm

Dijkstra_Algorithm/Dijkstra_Algorithm.java, Dijkstra_Algorithm/readme.md
=> Documentation and Implementation of Dijkstra’s Algorithm

kahn's algorithm
Implementing Topological Sort using **kahn's** algorithm
=> Kahn's Algorithm

Sieve of Earstosthenes/readme.md, Sieve of Earstosthenes/sieve.cpp
=> adding sieve of Erastosthenes

Fenwich_Tree.cpp
Fenwick Tree (also known as BIT) algorithm added
=> Fenwick tree Algo added

CycleDetectionDirectedGraph.cpp, README.md
Added reference to README about Cycle Detection
=> Added Cycle Detection in Directed Graph and Updated README

Number Theory/Binary_Exponentiation.cpp, Number Theory/Matrix_exponentiation.cpp, Number Theory/Primality_Test.cpp, Number Theory/Prime_Factorisation.cpp, Number Theory/Sieve_of_Eratosthenes.cpp, Number Theory/factorisation_using_sieve.cpp
Algorithms related to Number Theory
=> Number Theory added

Number Theory/FibonacciHuge.cpp, Number Theory/NthFibonacci.cpp, Number Theory/PisanoPeriod.cpp, Number Theory/PisanoPeriod_Fibonacci_SumLastDigit.cpp, Number Theory/PisanoPeriod_Fibonacci_SumSquares.cpp, Number Theory/PisanoPeriod_Nthfibonacci_last_digit.cpp
Introduced Pisano Period and its Applications with Fibonacci Numbers
=> Introduced Pisano Period and its Applications with Fibonacci Numbers

goldbachfinal.c
Goldbach's Conjecture -- says that any even  integer greater than 2 is the sum of two prime numbers (like 4 = 2 + 2;  8 = 3 + 5; 22 = 3 + 19 = 5 + 17 etc.).Here is a C program to verify the same
=> Goldbach's Conjecture

Iterative_Segment_Tree.cpp
Optimized iterative segment tree using Bit manipulation.
=> Added Iterative Segment Tree Code

D-NumberOfDifferentOnSegment.cpp
=> EDU section in codeforces D-NumberOfDifferentOnSegment

DutchNationalFlag.cpp
This algo helps to sort an array of 0,1,2 or any trio sorting items
=> DNS Algorithm

LCS.cpp
I have added the code to find the length of the longest common subsequence of 2 strings using Dynamic Programming approach.
=> Longest Common Subsequence problem using DP

Google Foobar/BreedingLikeRabbits.md, Google Foobar/BreedingLikeRabbits.py
references #117 added Google Foobar Question
=> Added foobar question

Searching Algos & Problems/TernarySearch.C
I have added the code to implement Ternary search in C. It takes input as the number of integers to be present in the array. It then inserts numbers in the array using a random function. It then chooses an element at random and searches for it using the TernS function.
=> Added TernarySearch

Problems and General Algos/SJF.c
Average Waiting Time and Turnaround Time for each Process included
=> Shortest Job First Algorithm in C

Google Foobar/Undercover-Underground.md, Google Foobar/Undercover-Underground.py
=> Added new Google Foobar problem

Google Foobar Challenge/Problem Statement - Fuel.md, Google Foobar Challenge/Problem-Statement- Bomb-Baby.md, Google Foobar Challenge/bomb_baby.py, Google Foobar Challenge/fuel-injection-perfection.py
Added two Google Foobar Challenge Round 3 Questions with their solution(with commented explanation) implemented in Python
1) Bomb Baby
2) Fuel Injection Perfection
=> Added Foobar Problems with Solution

Codechef-Solutions/June-Long-2020-CHFICRM/explanation.md, Codechef-Solutions/June-Long-2020-CHFICRM/solution.cpp, Codechef-Solutions/June-Long-2020-EOEO/explanation.md, Codechef-Solutions/June-Long-2020-EOEO/solution.cpp, Codechef-Solutions/June-Long-2020-EVENM/explanation.md, Codechef-Solutions/June-Long-2020-EVENM/solution.cpp
I have added 3 solutions for Codechef June Long 2020. A folder named Codechef-Solutions has been created. This contains sub-folders for each solution. Each subfolder contains a file named solution.cpp which contains the C++ code and an explanation.md file which contains the link to the question and the explanation.
=> Added 3 solutions and explanations for June Long 2020 in Codechef

Stacks/Readme.md, Stacks/StackArray.java, Stacks/StackLinkedList.java
In refrence to issue #140 
I am adding stack directory with readme file
=> Adding Stacks implementation using java 

Codechef-Solutions/August Long Challenge-2020/AnotherCardGame.py, Codechef-Solutions/August Long Challenge-2020/ChefWars.py.py, Codechef-Solutions/August Long Challenge-2020/Chef_And_linear_Chess.py, Codechef-Solutions/August Long Challenge-2020/README.md, Codechef-Solutions/August Long Challenge-2020/SmallestKMP.py
Added codechef solutions. @Vishal1003 Please review and suggest changes(if any). Thanks.
=> Added Codechef Solutions - August Long Challenge 2020
